data:
  root_path: ~/AOI_5_Khartoum
  image_product: PS-RGB
  crop_size: 224
  crop_scale: [0.3, 1.0]
  batch_size: 32
  num_workers: 8
  pin_memory: true

model:
  model_name: vit_tiny
  in_channels: 3
  patch_size: 16
  predictor_depth: 3
  predictor_embed_dim: 96

mask:
  allow_overlap: false
  aspect_ratio: [0.75, 1.5]
  enc_mask_scale: [0.85, 1.0]
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  pred_mask_scale: [0.15, 0.2]

optimization:
  ema: [0.996, 1.0]
  epochs: 1
  final_lr: 0.000001
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.0005
  start_lr: 0.0001
  warmup: 0
  weight_decay: 0.04

logging:
  folder: artifacts/jepa
  write_tag: geotiff_jepa

launcher:
  partition: null
  nodes: 1
  tasks_per_node: 1
  time_minutes: 30
